// The endpoint catalogue. This is the single source of truth for the OpenAPI
// spec (lib/openapi.js), the /api index, and the dashboard's API tab, so those
// three cannot drift apart. scripts/check-openapi.js diffs it against the
// routes Express actually registered and fails when they disagree.
//
// Fields: method, path, tag, summary, description?, params?, body?, curl?,
//         deprecated?, deprecationNote?

const B = (props, required) => ({ type: 'object', properties: props, required });
const str = (description, extra) => Object.assign({ type: 'string', description }, extra);
const num = (description, extra) => Object.assign({ type: 'number', description }, extra);
const int = (description, extra) => Object.assign({ type: 'integer', description }, extra);
const bool = (description, extra) => Object.assign({ type: 'boolean', description }, extra);

module.exports = [
  // -------------------------------------------------------------------------
  { id: 'getIndex', method: 'get', path: '/api', tag: 'Meta', open: true,
    summary: 'API index: what exists, whether a token is required, and where the spec lives',
    curl: 'curl -s {{base}}/api' },
  { id: 'getOpenapi', method: 'get', path: '/api/openapi.json', tag: 'Meta', open: true,
    summary: 'OpenAPI 3.1 specification for this API',
    curl: 'curl -s {{base}}/api/openapi.json' },
  { id: 'getLlmsTxt', method: 'get', path: '/api/llms.txt', tag: 'Meta', open: true,
    summary: 'Compact plain-text endpoint reference, cheap for an agent to read in one fetch',
    curl: 'curl -s {{base}}/api/llms.txt' },
  { id: 'getHealth', method: 'get', path: '/api/health', tag: 'Meta', open: true,
    summary: 'Liveness probe. Also reports whether an API token is required.',
    curl: 'curl -s {{base}}/api/health' },
  { id: 'getConnection', method: 'get', path: '/api/connection', tag: 'Meta',
    summary: 'Connection details for pointing another app at this regtest node',
    description: 'Returns the bitcoind RPC URL and cookie credentials, P2P and ZMQ endpoints, the Electrum connection string, and ready to run commands. On a non-regtest chain the credentials are withheld.',
    curl: 'curl -s {{base}}/api/connection' },
  { id: 'getStatus', method: 'get', path: '/api/status', tag: 'Meta',
    summary: 'One-call snapshot of chain, mempool, wallet, node, electrs and auto-mine',
    description: 'Built with per-subsystem error capture, so one dead subsystem degrades to a null field and an entry in errors[] rather than failing the whole response.',
    curl: 'curl -s {{base}}/api/status' },

  // -------------------------------------------------------------------------
  { id: 'faucet', method: 'post', path: '/api/faucet', tag: 'Test Driver',
    summary: 'Fund an address and confirm it in one call',
    description: 'Mines to the internal wallet first when there is no mature balance (regtest coinbase needs 100 confirmations), then sends, then mines the requested number of confirmations. Returns the exact outpoint.',
    body: B({
      address: str('Destination address. A fresh wallet address is generated when omitted.'),
      amount: num('Amount in BTC', { default: 1 }),
      confirmations: int('Blocks to mine after sending. 0 leaves the transaction in the mempool.', { default: 1, maximum: 100 }),
      feeRate: num('Fee rate in sat/vB', { default: 1 }),
      bootstrap: bool('Auto-mine to create a spendable balance when the wallet is empty', { default: true }),
      idempotencyKey: str('Replays the previous response for the same key for 10 minutes, so a timed-out retry cannot double fund')
    }),
    curl: 'curl -sX POST {{base}}/api/faucet -H \'Content-Type: application/json\' -d \'{"address":"bcrt1...","amount":1}\'' },
  { id: 'reorg', method: 'post', path: '/api/chain/reorg', tag: 'Test Driver',
    summary: 'Reorganise the chain to test how a wallet handles it',
    description: 'Invalidates the last `depth` blocks and mines `depth + extra` to replace them. Set includeMempool to false to mine EMPTY blocks, which is what actually leaves the disconnected transactions unconfirmed. Regtest only.',
    body: B({
      depth: int('How many blocks to disconnect', { minimum: 1 }),
      extra: int('Additional blocks to mine on top, so the new chain is strictly longer', { default: 1 }),
      includeMempool: bool('Mine normally (true) or mine empty blocks so disconnected transactions stay unconfirmed (false)', { default: true }),
      mineTo: str('Address to mine the replacement blocks to'),
      force: bool('Proceed even when auto-mine is running', { default: false })
    }, ['depth']),
    curl: 'curl -sX POST {{base}}/api/chain/reorg -H \'Content-Type: application/json\' -d \'{"depth":2,"includeMempool":false}\'' },
  { id: 'waitHeight', method: 'get', path: '/api/wait/height/:height', tag: 'Test Driver',
    summary: 'Block until the chain reaches a height',
    description: 'Returns HTTP 200 whether or not the condition was met; check the satisfied and timedOut booleans.',
    params: { height: int('Target block height') },
    query: { timeout: int('Seconds to wait', { default: 30 }), interval: int('Poll interval in ms', { default: 500 }) },
    curl: 'curl -s "{{base}}/api/wait/height/210?timeout=30"' },
  { id: 'waitTx', method: 'get', path: '/api/wait/tx/:txid', tag: 'Test Driver',
    summary: 'Block until a transaction reaches a confirmation count',
    description: 'Works for any transaction, not just wallet ones, because the bundled node runs with txindex enabled.',
    params: { txid: str('Transaction id') },
    query: { confirmations: int('Confirmations to wait for', { default: 1 }), timeout: int('Seconds to wait', { default: 30 }) },
    curl: 'curl -s "{{base}}/api/wait/tx/<txid>?confirmations=1&timeout=30"' },
  { id: 'waitMempool', method: 'get', path: '/api/wait/mempool/:txid', tag: 'Test Driver',
    summary: 'Block until a transaction appears in the mempool',
    params: { txid: str('Transaction id') },
    query: { timeout: int('Seconds to wait', { default: 30 }) },
    curl: 'curl -s "{{base}}/api/wait/mempool/<txid>?timeout=30"' },

  // -------------------------------------------------------------------------
  { id: 'logSources', method: 'get', path: '/api/logs/sources', tag: 'Logs',
    summary: 'List log sources and why any of them is unavailable',
    curl: 'curl -s {{base}}/api/logs/sources' },
  { id: 'logsBitcoind', method: 'get', path: '/api/logs/bitcoind', tag: 'Logs',
    summary: "Tail Bitcoin Core's debug.log",
    description: 'Reads only the tail of the file. Because of that, a filter searches the tail window rather than the whole log; the response reports scannedLines and truncatedHead so that is visible.',
    query: {
      lines: int('Lines to return after filtering', { default: 200, maximum: 5000 }),
      filter: str('Case-insensitive substring, or /regex/'),
      regex: bool('Treat filter as a regular expression', { default: false }),
      maxBytes: int('How many bytes from the end of the file to search', { default: 262144 })
    },
    curl: 'curl -s "{{base}}/api/logs/bitcoind?lines=100&filter=UpdateTip"' },
  { id: 'logsServer', method: 'get', path: '/api/logs/server', tag: 'Logs',
    summary: "The dashboard server's own console output",
    query: { limit: int('Entries to return', { default: 200 }), since: int('Return only entries after this seq'), level: str('Filter by log level'), filter: str('Substring or /regex/') },
    curl: 'curl -s "{{base}}/api/logs/server?limit=100"' },
  { id: 'logsRpc', method: 'get', path: '/api/logs/rpc', tag: 'Logs',
    summary: 'Structured record of every Bitcoin RPC call, with duration and error',
    query: { limit: int('Entries to return', { default: 100 }), since: int('Return only entries after this seq'), method: str('Filter by RPC method name'), errorsOnly: bool('Only failed calls') },
    curl: 'curl -s "{{base}}/api/logs/rpc?errorsOnly=true"' },
  { id: 'logsStream', method: 'get', path: '/api/logs/stream', tag: 'Logs',
    summary: 'Follow logs live over server-sent events',
    description: 'Use ?access_token= for auth here, because EventSource cannot set request headers. Plain polling of the endpoints above is easier for scripts.',
    query: { source: str('bitcoind, server or all', { default: 'bitcoind' }), lines: int('Backfill lines to send first', { default: 200 }) },
    curl: 'curl -sN "{{base}}/api/logs/stream?source=bitcoind&lines=20"' },
  { id: 'getDebugCategories', method: 'get', path: '/api/logs/debug-categories', tag: 'Logs',
    summary: "Bitcoin Core's active logging categories",
    curl: 'curl -s {{base}}/api/logs/debug-categories' },
  { id: 'setDebugCategories', method: 'post', path: '/api/logs/debug-categories', tag: 'Logs',
    summary: 'Turn Bitcoin Core debug logging categories on or off at runtime',
    body: B({ include: { type: 'array', items: { type: 'string' }, description: 'Categories to enable' }, exclude: { type: 'array', items: { type: 'string' }, description: 'Categories to disable' } }),
    curl: 'curl -sX POST {{base}}/api/logs/debug-categories -H \'Content-Type: application/json\' -d \'{"include":["mempool"]}\'' },

  // -------------------------------------------------------------------------
  { id: 'mine', method: 'post', path: '/api/mine', tag: 'Mining',
    summary: 'Mine blocks to an address',
    body: B({ blocks: int('Number of blocks', { default: 1 }), address: str('Address to mine to. A wallet address is used when omitted.') }),
    curl: 'curl -sX POST {{base}}/api/mine -H \'Content-Type: application/json\' -d \'{"blocks":1}\'' },
  { id: 'autoMineStart', method: 'post', path: '/api/mine/auto/start', tag: 'Mining',
    summary: 'Start mining blocks on an interval until stopped',
    body: B({ intervalSeconds: int('Seconds between batches'), blocks: int('Blocks per batch', { default: 1 }), durationMinutes: int('Optional run length; omit to run until stopped'), address: str('Address to mine to') }, ['intervalSeconds']),
    curl: 'curl -sX POST {{base}}/api/mine/auto/start -H \'Content-Type: application/json\' -d \'{"intervalSeconds":10,"blocks":1}\'' },
  { id: 'autoMineStop', method: 'post', path: '/api/mine/auto/stop', tag: 'Mining', summary: 'Stop the auto-mine job',
    curl: 'curl -sX POST {{base}}/api/mine/auto/stop' },
  { id: 'autoMineStatus', method: 'get', path: '/api/mine/auto/status', tag: 'Mining', summary: 'Auto-mine job status',
    curl: 'curl -s {{base}}/api/mine/auto/status' },
  { id: 'miningInfo', method: 'get', path: '/api/mining/info', tag: 'Mining', summary: 'getmininginfo',
    curl: 'curl -s {{base}}/api/mining/info' },

  // -------------------------------------------------------------------------
  { id: 'blockchainInfo', method: 'get', path: '/api/blockchain/info', tag: 'Node', summary: 'getblockchaininfo',
    curl: 'curl -s {{base}}/api/blockchain/info' },
  { id: 'networkInfo', method: 'get', path: '/api/network/info', tag: 'Node', summary: 'getnetworkinfo',
    curl: 'curl -s {{base}}/api/network/info' },
  { id: 'networkPeers', method: 'get', path: '/api/network/peers', tag: 'Node', summary: 'getpeerinfo',
    curl: 'curl -s {{base}}/api/network/peers' },
  { id: 'addNode', method: 'post', path: '/api/network/addnode', tag: 'Node', summary: 'Connect to a peer',
    body: B({ node: str('host:port'), command: str('add, remove or onetry', { default: 'add' }) }, ['node']) },
  { id: 'disconnectNode', method: 'post', path: '/api/network/disconnectnode', tag: 'Node', summary: 'Disconnect a peer',
    body: B({ address: str('Peer address'), nodeId: int('Peer id') }) },
  { id: 'estimateSmartFee', method: 'get', path: '/api/estimatesmartfee/:blocks', tag: 'Node', summary: 'estimatesmartfee for a confirmation target',
    params: { blocks: int('Confirmation target') } },
  { id: 'validateAddress', method: 'get', path: '/api/validateaddress/:address', tag: 'Node', summary: 'Validate an address',
    params: { address: str('Address to validate') }, curl: 'curl -s {{base}}/api/validateaddress/bcrt1...' },
  { id: 'rpcPassthrough', method: 'post', path: '/api/rpc', tag: 'Node',
    summary: 'Call any Bitcoin Core RPC method directly',
    description: 'The supported way to reach bitcoind from another app: the node\'s own RPC port is not published to the host in the bundled compose file.',
    body: B({ method: str('RPC method name'), params: { type: 'array', description: 'Positional parameters' } }, ['method']),
    curl: 'curl -sX POST {{base}}/api/rpc -H \'Content-Type: application/json\' -d \'{"method":"getblockchaininfo","params":[]}\'' },

  // -------------------------------------------------------------------------
  { id: 'mempoolInfo', method: 'get', path: '/api/mempool/info', tag: 'Mempool', summary: 'getmempoolinfo',
    curl: 'curl -s {{base}}/api/mempool/info' },
  { id: 'mempoolRaw', method: 'get', path: '/api/mempool/raw', tag: 'Mempool', summary: 'getrawmempool',
    query: { verbose: bool('Include per-transaction detail', { default: false }) },
    curl: 'curl -s "{{base}}/api/mempool/raw?verbose=true"' },

  // -------------------------------------------------------------------------
  { id: 'blockBest', method: 'get', path: '/api/block/best', tag: 'Blocks', summary: 'Best block hash',
    curl: 'curl -s {{base}}/api/block/best' },
  { id: 'blockByHeight', method: 'get', path: '/api/block/height/:height', tag: 'Blocks', summary: 'Get a block by height',
    params: { height: int('Block height') }, curl: 'curl -s {{base}}/api/block/height/1' },
  { id: 'blockByHash', method: 'get', path: '/api/block/:hash', tag: 'Blocks', summary: 'Get a block by hash',
    params: { hash: str('Block hash') }, query: { verbosity: int('getblock verbosity', { default: 1 }) } },

  // -------------------------------------------------------------------------
  { id: 'walletInfo', method: 'get', path: '/api/wallet/info', tag: 'Wallet', summary: 'getwalletinfo',
    curl: 'curl -s {{base}}/api/wallet/info' },
  { id: 'walletBalance', method: 'get', path: '/api/wallet/balance', tag: 'Wallet', summary: 'Confirmed and unconfirmed balance',
    curl: 'curl -s {{base}}/api/wallet/balance' },
  { id: 'walletList', method: 'get', path: '/api/wallet/list', tag: 'Wallet', summary: 'List loaded wallets' },
  { id: 'walletCreate', method: 'post', path: '/api/wallet/create', tag: 'Wallet', summary: 'Create a wallet',
    description: 'descriptors defaults to true. Bitcoin Core no longer supports legacy wallets, so passing false will fail.',
    body: B({ name: str('Wallet name'), disablePrivateKeys: bool('Watch-only wallet', { default: false }), blank: bool('Create without keys', { default: false }), passphrase: str('Encryption passphrase'), avoidReuse: bool('Avoid address reuse', { default: false }), descriptors: bool('Descriptor wallet', { default: true }) }, ['name']) },
  { id: 'walletLoad', method: 'post', path: '/api/wallet/load', tag: 'Wallet', summary: 'Load a wallet', body: B({ name: str('Wallet name') }, ['name']) },
  { id: 'walletNewAddress', method: 'post', path: '/api/wallet/newaddress', tag: 'Wallet', summary: 'Generate a receiving address',
    body: B({ label: str('Address label'), addressType: str('bech32, bech32m, p2sh-segwit or legacy', { default: 'bech32' }) }),
    curl: 'curl -sX POST {{base}}/api/wallet/newaddress -H \'Content-Type: application/json\' -d \'{"addressType":"bech32"}\'' },
  { id: 'walletAddresses', method: 'get', path: '/api/wallet/addresses', tag: 'Wallet', summary: 'List addresses with receive totals' },
  { id: 'walletAddressInfo', method: 'get', path: '/api/wallet/addressinfo/:address', tag: 'Wallet', summary: 'getaddressinfo', params: { address: str('Address') } },
  { id: 'walletSend', method: 'post', path: '/api/wallet/send', tag: 'Wallet', summary: 'Send BTC to an address',
    body: B({ address: str('Destination'), amount: num('Amount in BTC'), comment: str('Comment'), commentTo: str('Comment to'), subtractFee: bool('Take the fee from the amount', { default: false }), replaceable: bool('Signal RBF', { default: true }), feeRate: num('sat/vB', { default: 1 }) }, ['address', 'amount']),
    curl: 'curl -sX POST {{base}}/api/wallet/send -H \'Content-Type: application/json\' -d \'{"address":"bcrt1...","amount":0.1}\'' },
  { id: 'walletSendMany', method: 'post', path: '/api/wallet/sendmany', tag: 'Wallet', summary: 'Send to several addresses at once',
    body: B({ amounts: { type: 'object', description: 'Map of address to BTC amount' }, comment: str('Comment'), subtractFeeFrom: { type: 'array', items: { type: 'string' } }, replaceable: bool('Signal RBF', { default: true }), feeRate: num('sat/vB', { default: 1 }) }, ['amounts']) },
  { id: 'walletTransactions', method: 'get', path: '/api/wallet/transactions', tag: 'Wallet', summary: 'Recent wallet transactions',
    query: { count: int('How many', { default: 20 }), skip: int('Offset', { default: 0 }) } },
  { id: 'walletUtxos', method: 'get', path: '/api/wallet/utxos', tag: 'Wallet', summary: 'List unspent outputs',
    query: { minconf: int('Minimum confirmations', { default: 0 }), maxconf: int('Maximum confirmations') },
    curl: 'curl -s {{base}}/api/wallet/utxos' },
  { id: 'walletImportAddress', method: 'post', path: '/api/wallet/importaddress', tag: 'Wallet', deprecated: true,
    summary: 'Import a watch-only address',
    deprecationNote: 'importaddress needs a legacy wallet, which Bitcoin Core has removed. This endpoint now falls back to importdescriptors with an addr() descriptor.',
    body: B({ address: str('Address to watch'), label: str('Label'), rescan: bool('Rescan the chain', { default: false }) }, ['address']) },
  { id: 'walletImportPrivkey', method: 'post', path: '/api/wallet/importprivkey', tag: 'Wallet', deprecated: true,
    summary: 'Import a private key',
    deprecationNote: 'importprivkey needs a legacy wallet, which Bitcoin Core has removed. This endpoint now falls back to importdescriptors with a wpkh() descriptor.',
    body: B({ privkey: str('WIF private key'), label: str('Label'), rescan: bool('Rescan the chain', { default: false }) }, ['privkey']) },
  { id: 'walletDumpPrivkey', method: 'get', path: '/api/wallet/dumpprivkey/:address', tag: 'Wallet', deprecated: true,
    summary: 'Reveal the private key for an address',
    deprecationNote: 'dumpprivkey needs a legacy wallet, which Bitcoin Core has removed. Use GET /api/wallet/descriptors instead.',
    params: { address: str('Address') } },
  { id: 'walletDescriptors', method: 'get', path: '/api/wallet/descriptors', tag: 'Wallet',
    summary: 'List the wallet descriptors, including private keys',
    description: 'The descriptor-wallet replacement for dumpprivkey.',
    query: { private: bool('Include private keys', { default: true }) },
    curl: 'curl -s {{base}}/api/wallet/descriptors' },
  { id: 'walletImportDescriptors', method: 'post', path: '/api/wallet/importdescriptors', tag: 'Wallet',
    summary: 'Import descriptors into the wallet',
    body: B({ requests: { type: 'array', description: 'Array of importdescriptors request objects' } }, ['requests']),
    curl: 'curl -sX POST {{base}}/api/wallet/importdescriptors -H \'Content-Type: application/json\' -d \'{"requests":[{"desc":"addr(bcrt1...)#checksum","timestamp":"now"}]}\'' },

  // -------------------------------------------------------------------------
  { id: 'txGet', method: 'get', path: '/api/transaction/:txid', tag: 'Transactions', summary: 'Wallet transaction detail', params: { txid: str('Transaction id') } },
  { id: 'txRaw', method: 'get', path: '/api/transaction/:txid/raw', tag: 'Transactions', summary: 'Raw transaction, hex or decoded',
    params: { txid: str('Transaction id') }, query: { verbose: bool('Return decoded JSON', { default: false }) } },
  { id: 'txDecode', method: 'post', path: '/api/transaction/decode', tag: 'Transactions', summary: 'Decode a raw transaction', body: B({ hex: str('Raw transaction hex') }, ['hex']) },
  { id: 'txCreate', method: 'post', path: '/api/transaction/create', tag: 'Transactions', summary: 'Build an unsigned raw transaction',
    body: B({ inputs: { type: 'array' }, outputs: { type: 'array' }, locktime: int('Locktime', { default: 0 }), replaceable: bool('Signal RBF', { default: true }) }, ['inputs', 'outputs']) },
  { id: 'txFund', method: 'post', path: '/api/transaction/fund', tag: 'Transactions', summary: 'Add inputs and change to a raw transaction', body: B({ hex: str('Raw transaction hex'), options: { type: 'object' } }, ['hex']) },
  { id: 'txSign', method: 'post', path: '/api/transaction/sign', tag: 'Transactions', summary: 'Sign a raw transaction with the wallet', body: B({ hex: str('Raw transaction hex') }, ['hex']) },
  { id: 'txSend', method: 'post', path: '/api/transaction/send', tag: 'Transactions', summary: 'Broadcast a raw transaction',
    body: B({ hex: str('Raw transaction hex'), maxFeeRate: num('Maximum fee rate, 0 to disable the check') }, ['hex']) },
  { id: 'txTestMempoolAccept', method: 'post', path: '/api/transaction/testmempoolaccept', tag: 'Transactions', summary: 'Dry-run mempool acceptance',
    body: B({ rawtxs: { type: 'array', items: { type: 'string' } }, maxFeeRate: num('Maximum fee rate') }, ['rawtxs']) },
  { id: 'txBumpFee', method: 'post', path: '/api/transaction/bumpfee', tag: 'Transactions', summary: 'Replace a transaction with a higher fee (RBF)',
    body: B({ txid: str('Transaction to replace'), options: { type: 'object' } }, ['txid']) },
  { id: 'txCancel', method: 'post', path: '/api/transaction/cancel', tag: 'Transactions', summary: 'Cancel an unconfirmed transaction by replacing it with a self-send',
    body: B({ txid: str('Transaction to cancel') }, ['txid']) },

  // -------------------------------------------------------------------------
  { id: 'psbtCreate', method: 'post', path: '/api/psbt/create', tag: 'PSBT', summary: 'Create a PSBT',
    body: B({ inputs: { type: 'array' }, outputs: { type: 'array' }, locktime: int('Locktime', { default: 0 }), replaceable: bool('Signal RBF', { default: true }) }, ['inputs', 'outputs']) },
  { id: 'psbtDecode', method: 'post', path: '/api/psbt/decode', tag: 'PSBT', summary: 'Decode a PSBT', body: B({ psbt: str('Base64 PSBT') }, ['psbt']) },
  { id: 'psbtAnalyze', method: 'post', path: '/api/psbt/analyze', tag: 'PSBT', summary: 'Analyze a PSBT', body: B({ psbt: str('Base64 PSBT') }, ['psbt']) },
  { id: 'psbtProcess', method: 'post', path: '/api/psbt/process', tag: 'PSBT', summary: 'Sign a PSBT with the wallet', body: B({ psbt: str('Base64 PSBT') }, ['psbt']) },
  { id: 'psbtFinalize', method: 'post', path: '/api/psbt/finalize', tag: 'PSBT', summary: 'Finalize a PSBT into a raw transaction', body: B({ psbt: str('Base64 PSBT') }, ['psbt']) },

  // -------------------------------------------------------------------------
  { id: 'chainReset', method: 'post', path: '/api/chain/reset', tag: 'Chain',
    summary: 'Invalidate every block back to genesis',
    description: 'Destructive. Requires {"confirm":"RESET"}. The wallet loses all coins.',
    body: B({ confirm: str('Must be the literal string RESET') }, ['confirm']) },
  { id: 'chainReconsider', method: 'post', path: '/api/chain/reconsider', tag: 'Chain',
    summary: 'Reconsider invalidated blocks',
    body: B({ blockHash: str('Block to reconsider. Defaults to the block at height 1.') }) },

  // -------------------------------------------------------------------------
  { id: 'electrsHealth', method: 'get', path: '/api/electrs/health', tag: 'Electrs', summary: 'Electrs reachability and banner',
    curl: 'curl -s {{base}}/api/electrs/health' },
  { id: 'electrsInfo', method: 'get', path: '/api/electrs/info', tag: 'Electrs', summary: 'Electrum connection details for external wallets',
    curl: 'curl -s {{base}}/api/electrs/info' },
  { id: 'electrsAddress', method: 'get', path: '/api/electrs/address/:address', tag: 'Electrs', summary: 'Address balance and transaction count', params: { address: str('Address') } },
  { id: 'electrsAddressTxs', method: 'get', path: '/api/electrs/address/:address/txs', tag: 'Electrs', summary: 'Address transaction history', params: { address: str('Address') } },
  { id: 'electrsAddressUtxo', method: 'get', path: '/api/electrs/address/:address/utxo', tag: 'Electrs', summary: 'Address unspent outputs', params: { address: str('Address') } },
  { id: 'electrsTx', method: 'get', path: '/api/electrs/tx/:txid', tag: 'Electrs', summary: 'Raw transaction from Electrs', params: { txid: str('Transaction id') } },
  { id: 'electrsTipHeight', method: 'get', path: '/api/electrs/blocks/tip/height', tag: 'Electrs', summary: 'Chain tip height as seen by Electrs',
    curl: 'curl -s {{base}}/api/electrs/blocks/tip/height' },
  { id: 'electrsFeeEstimates', method: 'get', path: '/api/electrs/fee-estimates', tag: 'Electrs', summary: 'Fee estimates by confirmation target, in sat/vB',
    curl: 'curl -s {{base}}/api/electrs/fee-estimates' }
];
